In [23]:
import pandas as pd
import os

# Set project directory
project_dir = '/Users/omkar/Documents/SmartShop'
os.chdir(project_dir)

# Verify current working directory
print(f"Current directory: {os.getcwd()}")

Current directory: /Users/omkar/Documents/SmartShop

In [65]:
#### Data loader
Column_name = ['supermarket',"prices_(£)",'names','date','category','own_brand']
sains_data = pd.read_csv('data/All_Data_Sains.csv', usecols=Column_name)
#### Reading the brand - product csv
brand_df = pd.read_csv("/Users/omkar/Documents/SmartShop/notebook/llm_master_brand.csv",header=0,names=['names','brand'])

In [25]:
#### Data Preprocessing
import re 
## Changing the Date format.
def change_date_format(df:pd.DataFrame) -> pd.DataFrame:

    if "date" in df.columns:
        print("Date Column Processing")
        df['date'] = pd.to_datetime(df['date'], format='%Y%m%d')
        print("Date Column Processed")
    else:
        return None
    return df


## Extracting the packet size from the name column and creating a new column for it.

def extract_package_size(df:pd.DataFrame) -> pd.DataFrame:
    df['extracted_pack_info'] = df['names'].str.split().apply(lambda words: [w for w in words if re.search(r'\d', w)])
    return df


## Add a new column "Brand" and replace the supermarket name with the brand name with own_brand == True.
def replace_house_brand(df:pd.DataFrame)->pd.DataFrame:
    df.loc[df['own_brand'] == True, 'Brand'] = df['supermarket']
    return df

In [26]:
import re
import pandas as pd

def normalize_pack_info(df, col="extracted_pack_info"):
    
    def parse_pack(x):
        # Handle None / NaN safely
        if x is None:
            return None, None, None
        
        if isinstance(x, float) and pd.isna(x):
            return None, None, None
        
        # Convert list → string
        if isinstance(x, (list, tuple)):
            x = " ".join(map(str, x))
        else:
            x = str(x)
        
        x = x.lower()
        x = re.sub(r"[^\w\.x ]", " ", x)  # clean junk
        
        pack_count = None
        unit_size = None
        unit_type = None
        
        # Case 1: 4x85g
        match = re.search(r"(\d+)\s*x\s*(\d+)(g|ml|kg|l)", x)
        if match:
            return int(match.group(1)), int(match.group(2)), match.group(3)
        
        # Case 2: size + count
        size_match = re.search(r"(\d+)(g|ml|kg|l)", x)
        count_match = re.findall(r"\b\d+\b", x)
        
        if size_match:
            unit_size = int(size_match.group(1))
            unit_type = size_match.group(2)
        
        # Extract count carefully
        if count_match:
            nums = list(map(int, count_match))
            
            # remove unit_size if present
            if unit_size in nums:
                nums.remove(unit_size)
            
            if nums:
                pack_count = nums[0]
        
        # Case 3: x30
        if pack_count is None:
            match = re.search(r"x(\d+)", x)
            if match:
                pack_count = int(match.group(1))
        
        return pack_count, unit_size, unit_type
    
    parsed = df[col].apply(parse_pack)
    
    df["pack_count"] = parsed.apply(lambda x: x[0])
    df["unit_size"] = parsed.apply(lambda x: x[1])
    df["unit_type"] = parsed.apply(lambda x: x[2])
    
    return df

In [27]:
transform1 = change_date_format(sains_data)
print("Transformation Phase 1 Completed ")
transform2 = extract_package_size(transform1)
print("Transformation Phase 2 Completed ")
transform3 = replace_house_brand(transform2)
print("Transformation Phase 3 Completed ")
transform4 = normalize_pack_info(transform3)
print("Transformation Phase 4 Completed ")

Date Column Processing
Date Column Processed
Transformation Phase 1 Completed
Transformation Phase 2 Completed
Transformation Phase 3 Completed
Transformation Phase 4 Completed

In [28]:
transform4.head()

,supermarket,prices_(£),names,date,category,own_brand,extracted_pack_info,Brand,pack_count,unit_size,unit_type
0,Sains,6.00,Bassetts Vitamins Omega-3 & Multivits 3-6 Soft...,2024-04-13,baby_products,False,"[Omega-3, 3-6, x30]",NaN,3.0,NaN,NaN
1,Sains,2.35,Annabel Karmel Chicken & Potato Pie Toddler Me...,2024-04-13,baby_products,False,"[200g, 12]",NaN,12.0,200.0,g
2,Sains,2.35,Annabel Karmel Beef Cottage Pie Toddler Meal 2...,2024-04-13,baby_products,False,"[200g, 12]",NaN,12.0,200.0,g
3,Sains,2.15,Yeo Valley Organic Little Yeos 4x85g,2024-04-13,baby_products,False,[4x85g],NaN,4.0,85.0,g
4,Sains,0.75,The Collective Suckies Strawberry Kids Yoghurt...,2024-04-13,baby_products,False,[90g],NaN,NaN,90.0,g

In [7]:
final_dataset_columns = ['supermarket','price','product','date','category','Brand','pack_count','unit_size','unit_type']

In [29]:
#### Creating a Subset of the dataframe based on the brands. 
#### 2 subset will be created. inhouse-brand set and 3rd party set. 

inhouse_products = transform4[transform4['own_brand'] == True]
third_party_brands = transform4[transform4['own_brand'] == False]

### Brand Extraction

In [30]:
def normalize_brands(brands_list):
    import pandas as pd
    import re
    
    clean_map = {}
    
    for b in brands_list:
        if pd.isna(b):
            continue
        
        original = str(b).strip()
        
        # normalize
        norm = original.lower()
        norm = re.sub(r"[’']", "", norm)     # remove apostrophes
        norm = re.sub(r"[^a-z0-9\s]", " ", norm)  # remove special chars
        norm = re.sub(r"\s+", " ", norm).strip()  # remove extra spaces
        
        # keep first clean version as canonical
        if norm not in clean_map:
            clean_map[norm] = original
    
    return clean_map

In [31]:
brand_map = normalize_brands(brand_df['brand'].unique())
brand_map

{'maryland': 'Maryland',
 'weetabix': 'Weetabix',
 'walkers': "Walker's",
 'stamford street co': 'Stamford Street Co.',
 'cravendale': 'Cravendale',
 'js': 'JS',
 'heinz': 'Heinz',
 'napolina': 'Napolina',
 'oatly': 'Oatly',
 'alpro': 'Alpro',
 'ktc': 'KTC',
 'mcvities': "McVitie's",
 'princes': 'Princes',
 'hula hoops': 'Hula Hoops',
 'jacobs': "Jacob's",
 'batchelors': 'Batchelors',
 'pom bear': 'Pom-Bear',
 'birds eye': 'Birds Eye',
 'kitkat': 'KitKat',
 'diet coke': 'Diet Coke',
 'cadbury': 'Cadbury',
 'tilda': 'Tilda',
 'kit kat': 'Kit Kat',
 'ambrosia': 'Ambrosia',
 'pringles': 'Pringles',
 'kerrygold': 'Kerrygold',
 'doritos': 'Doritos',
 'sensations': 'Sensations',
 'branston': 'Branston',
 'jus rol': 'Jus-Rol',
 'happy egg': 'Happy Egg',
 'terrys': "Terry's",
 'kettle chips': 'Kettle Chips',
 'dolmio': 'Dolmio',
 'yeo valley': 'Yeo Valley',
 'mccoys': "McCoy's",
 'soreen': 'Soreen',
 'oreo': 'Oreo',
 'tunnocks': "Tunnock's",
 'quaker': 'Quaker',
 'lindt': 'Lindt',
 'bisto': 'Bisto',
 'nescaf': 'Nescafé',
 'kelloggs': "Kellogg's",
 'nature valley': 'Nature Valley',
 'petits filous': 'Petits Filous',
 'green giant': 'Green Giant',
 'yorkshire tea': 'Yorkshire Tea',
 'hellmanns': "Hellmann's",
 'mccain': 'McCain',
 'farrows': "Farrow's",
 'pot noodle': 'Pot Noodle',
 'tyrrells': 'Tyrrells',
 'marmite': 'Marmite',
 'skips': 'Skips',
 'snack a jacks': 'Snack a Jacks',
 'sacla': 'Sacla',
 'stork': 'Stork',
 'go ahead': 'Go Ahead',
 'ko lee': 'Ko-Lee',
 'green blacks': "Green & Black's",
 'magnum': 'Magnum',
 'old el paso': 'Old El Paso',
 'kallo': 'Kallo',
 'foxs': "Fox's",
 'del monte': 'Del Monte',
 'vitalite': 'Vitalite',
 'quorn': 'Quorn',
 'loyd grossman': 'Loyd Grossman',
 'bonne maman': 'Bonne Maman',
 'barny': 'Barny',
 'maltesers': 'Maltesers',
 'tetley': 'Tetley',
 'galaxy': 'Galaxy',
 'smiths': 'Smiths',
 'ryvita': 'Ryvita',
 'whole earth': 'Whole Earth',
 'rude health': 'Rude Health',
 'bahlsen': 'Bahlsen',
 'unknown': 'Unknown',
 'smarties': 'Smarties',
 'kingsfood': 'Kingsfood',
 'knorr': 'Knorr',
 'peperami': 'Peperami',
 'gia': 'Gia',
 'rowse': 'Rowse',
 'hp': 'HP',
 'foxs biscuits': "Fox's Biscuits",
 'paxo': 'Paxo',
 'fever tree': 'Fever Tree',
 'mars': 'Mars',
 'toffee crisp': 'Toffee Crisp',
 'oxo': 'Oxo',
 'haribo': 'Haribo',
 'san pellegrino': 'San Pellegrino',
 'merchant gourmet': 'Merchant Gourmet',
 'hartleys': "Hartley's",
 'aero': 'Aero',
 'pg tips': 'PG tips',
 'bear': 'BEAR',
 'de cecco': 'De Cecco',
 'sunny': 'Sunny',
 'koko': 'Koko',
 'scotts porage': "Scott's Porage",
 'eat natural': 'Eat Natural',
 'heck': 'Heck',
 'nairns': "Nairn's",
 'lotus biscoff': 'Lotus Biscoff',
 'nestle': 'Nestle',
 'nakd': 'Nakd',
 'cauldron': 'Cauldron',
 'belvita': 'Belvita',
 'kp': 'KP',
 'after eight': 'After Eight',
 'carrs': "Carr's",
 'ready brek': 'Ready Brek',
 'butterkist': 'Butterkist',
 'colmans': "Colman's",
 'nescafe': 'Nescafe',
 'arla': 'Arla',
 'grahams': "Graham's",
 'flahavans': "Flahavan's",
 'jordans': 'Jordans',
 'bounty': 'Bounty',
 'lavazza': 'Lavazza',
 'frys': "Fry's",
 'cirio': 'Cirio',
 'sarsons': "Sarson's",
 'nutella': 'Nutella',
 'snickers': 'Snickers',
 'border': 'Border',
 'black farmer': 'Black Farmer',
 'karyatis': 'Karyatis',
 'mutti': 'Mutti',
 'sharwoods': "Sharwood's",
 'mr kipling': 'Mr Kipling',
 'kinder': 'Kinder',
 'the coconut collaborative': 'The Coconut Collaborative',
 'pataks': "Patak's",
 'lea perrins': 'Lea & Perrins',
 'carnation': 'Carnation',
 'very lazy': 'Very Lazy',
 'alpen': 'Alpen',
 'mazola': 'Mazola',
 'homepride': 'Homepride',
 'baxters': 'Baxters',
 'trebor': 'Trebor',
 'propercorn': 'Propercorn',
 'maldon': 'Maldon',
 'rowntrees': 'Rowntree’s',
 'sundora': 'Sundora',
 'werthers original': "Werther's Original",
 'weight watchers': 'Weight Watchers',
 'frylight': 'Frylight',
 'frank coopers': "Frank Cooper's",
 'glenryck': 'Glenryck',
 'popchips': 'Popchips',
 'blue dragon': 'Blue Dragon',
 'penn state': 'Penn State',
 'shreddies': 'Shreddies',
 'douwe egberts': 'Douwe Egberts',
 'kenco': 'Kenco',
 'fruit shoot': 'Fruit Shoot',
 'innocent': 'Innocent',
 'twinings': 'Twinings',
 'dailys': "Daily's",
 'yorkie': 'Yorkie',
 'haagen dazs': 'Haagen-Dazs',
 'maille': 'Maille',
 'm ms': "M&M's",
 'sweetex': 'Sweetex',
 'sainsburys': 'Sainsbury’s',
 'geetas': "Geeta's",
 'moma': 'MOMA',
 'quality street': 'Quality Street',
 'graze': 'Graze',
 'canderel': 'Canderel',
 'mug shot': 'Mug Shot',
 'fish': 'Fish!',
 'marigold': 'Marigold',
 'extra': 'Extra',
 'fridge raiders': 'Fridge Raiders',
 'the snack organisation': 'The Snack Organisation',
 'caxton': 'Caxton',
 'mama': 'Mama',
 'angel delight': 'Angel Delight',
 'options': 'Options',
 'campbells': "Campbell's",
 'milkybar': 'Milkybar',
 'wagon wheels': 'Wagon Wheels',
 'hovis': 'Hovis',
 'urban fruit': 'Urban Fruit',
 'krisprolls': 'Krisprolls',
 'plenish': 'Plenish',
 'yorkshire gold': 'Yorkshire Gold',
 'filippo berio': 'Filippo Berio',
 'trek': 'TREK',
 'clarks': 'Clarks',
 'the jolly hog': 'The Jolly Hog',
 'the fruit factory': 'The Fruit Factory',
 'ritz': 'Ritz',
 'spam': 'Spam',
 'tuc': 'Tuc',
 'amoy': 'Amoy',
 'polo': 'Polo',
 'yutaka': 'Yutaka',
 'ocean spray': 'Ocean Spray',
 'cheerios': 'Cheerios',
 'fareshare': 'FareShare',
 'flora': 'Flora',
 'mori nu': 'Mori-Nu',
 'ferrero rocher': 'Ferrero Rocher',
 'twix': 'Twix',
 'bernard matthews': 'Bernard Matthews',
 'kikkoman': 'Kikkoman',
 'crosta mollica': 'Crosta & Mollica',
 'desi': 'Desi',
 'robertsons': "Robertson's",
 'schar': 'Schar',
 'the groovy food company': 'The Groovy Food Company',
 'allinson': 'Allinson',
 'ainsley harriott': 'Ainsley Harriott',
 'lyles': "Lyle's",
 'bens original': 'Bens Original',
 'mrs crimbles': "Mrs Crimble's",
 'properchips': 'Properchips',
 'sainsburys flourish': 'Sainsbury’s Flourish',
 'tabasco': 'Tabasco',
 'fray bentos': 'Fray Bentos',
 'bovril': 'Bovril',
 'meridian': 'Meridian',
 'nissin': 'Nissin',
 'off the eaten path': 'Off the Eaten Path',
 'crisp n dry': "Crisp 'N' Dry",
 'califia farms': 'Califia Farms',
 'john west': 'John West',
 'pizza express': 'Pizza Express',
 'guinness': 'Guinness',
 'lizis': "Lizi's",
 'birds': "Bird's",
 'saxa': 'Saxa',
 'holy moly': 'Holy Moly',
 'mikado': 'Mikado',
 'tassimo': 'Tassimo',
 'warburtons': 'Warburtons',
 'opies': 'Opies',
 'sprite': 'Sprite',
 'dole': 'Dole',
 'pepsi max': 'Pepsi Max',
 'calypso': 'Calypso',
 'ovaltine': 'Ovaltine',
 'dr oetker': 'Dr. Oetker',
 'nandos': "Nando's",
 'capri sun': 'Capri-Sun',
 'genius': 'Genius',
 'garners': "Garner's",
 'billingtons': "Billington's",
 'whitworths': 'Whitworths',
 'toblerone': 'Toblerone',
 'the collective': 'The Collective',
 'fibre one': 'Fibre One',
 'panda': 'Panda',
 'milky way': 'Milky Way',
 'swizzels': 'Swizzels',
 'rombouts': 'Rombouts',
 'dunns river': "Dunn's River",
 'doves farm': 'Doves Farm',
 'lion': 'LION',
 'irish yogurts': 'Irish Yogurts',
 'dorset cereals': 'Dorset Cereals',
 'clarence court': 'Clarence Court',
 'cornish sea salt co': 'Cornish Sea Salt Co',
 'horlicks': 'Horlicks',
 'peters yard': "Peter's Yard",
 'pukka': 'Pukka',
 'nik naks': 'Nik Naks',
 'doria doriano': 'Doria Doriano',
 'ritter sport': 'Ritter Sport',
 'island delight': 'Island Delight',
 'freee': 'Freee',
 'ye olde oak': 'Ye Olde Oak',
 'lajkonik': 'Lajkonik',
 'borderfields': 'Borderfields',
 'north staffordshire': 'North Staffordshire',
 'maynards bassetts': 'Maynards Bassetts',
 'starbucks': 'Starbucks',
 'post': 'Post',
 'deliciously ella': 'Deliciously Ella',
 'natures finest': "Nature's Finest",
 'maggi': 'Maggi',
 'veetee': 'Veetee',
 'daddies': 'Daddies',
 'fudco': 'Fudco',
 'fullgreen': 'Fullgreen',
 'costa coffee': 'Costa Coffee',
 'linwoods': 'Linwoods',
 'losalt': 'LoSalt',
 'itsu': 'itsu',
 'chicken tonight': 'Chicken Tonight',
 'atora': 'Atora',
 'cofresh': 'Cofresh',
 'indo mie': 'Indo Mie',
 'skippy': 'Skippy',
 'la doria': 'La Doria',
 'menier': 'Menier',
 'mrs elswood': 'Mrs Elswood',
 'mai thai': 'Mai Thai',
 'idahoan': 'Idahoan',
 'natures path': "Nature's Path",
 'roses': "Rose's",
 'odysea': 'Odysea',
 'old jamaica': 'Old Jamaica',
 'tick tock': 'Tick Tock',
 'tidmans': "Tidman's",
 'the spice tailor': 'The Spice Tailor',
 'goldenfry': 'Goldenfry',
 'wikinger': 'Wikinger',
 'lancashire farm': 'Lancashire Farm',
 'mr porky': 'Mr Porky',
 'st dalfour': 'St. Dalfour',
 'dr karg': 'Dr Karg',
 'summer pride': 'Summer Pride',
 'splenda': 'Splenda',
 'elephant': 'Elephant',
 'parsons': 'Parsons',
 'henry goodes': "Henry Goode's",
 'rolo': 'Rolo',
 'goodfellas': "Goodfella's",
 'silver spoon': 'Silver Spoon',
 'vadasz': 'Vadasz',
 'ristorante': 'Ristorante',
 'mcdougalls': 'McDougalls',
 'lor': "L'OR",
 'munchies': 'Munchies',
 'stagg': 'Stagg',
 'gallo': 'Gallo',
 'kind': 'Kind',
 'carousel': 'Carousel',
 'sour patch kids': 'Sour Patch Kids',
 'border biscuits': 'Border Biscuits',
 'walkers wotsits': 'Walkers Wotsits',
 'il casolare': 'Il Casolare',
 'jamie oliver': 'Jamie Oliver',
 'wrights': "Wright's",
 'flipz': 'Flipz',
 'snack organisation': 'Snack Organisation',
 'auntys': "Aunty's",
 'taylors of harrogate': 'Taylors of Harrogate',
 'askeys': 'Askeys',
 'tiptree': 'Tiptree',
 'mackays': 'Mackays',
 'rakusens': "Rakusen's",
 'guylian': 'Guylian',
 'fuel10k': 'FUEL10K',
 'top taste': 'Top Taste',
 'buckwud': 'Buckwud',
 'eazypop': 'Eazypop',
 'naturli': 'Naturli',
 'pip nut': 'Pip & Nut',
 'littleover': 'Littleover',
 'belazu': 'Belazu',
 'bare naked': 'Bare Naked',
 'maynards': 'Maynards',
 'irwins': "Irwin's",
 'pipers': 'Pipers',
 'betty crocker': 'Betty Crocker',
 'bendicks': 'Bendicks',
 'cookie crisp': 'Cookie Crisp',
 'levi roots': 'Levi Roots',
 'lyons': 'Lyons',
 'the real pork co': 'The Real Pork Co.',
 'maoam': 'Maoam',
 'milko': 'Milko',
 'aspall': 'Aspall',
 'truvia': 'Truvia',
 'thai taste': 'Thai Taste',
 'fruit bowl': 'Fruit Bowl',
 'polish specialities': 'Polish Specialities',
 'siro': 'Siro',
 'clearspring': 'Clearspring',
 'schweppes': 'Schweppes',
 'arla jord': 'Arla Jord',
 'merba': 'Merba',
 'clipper': 'Clipper',
 'gressingham': 'Gressingham',
 'franks redhot': "Frank's Redhot",
 'ambassador': 'Ambassador',
 'kolee': 'Kolee',
 'loacker': 'Loacker',
 'jif': 'Jif',
 'monster energy': 'Monster Energy',
 'foresight': 'Foresight',
 'tonys chocolonely': "Tony's Chocolonely",
 'tate lyle': 'Tate & Lyle',
 'lee kum kee': 'Lee Kum Kee',
 'weight watchers from heinz': 'Weight Watchers from Heinz',
 'mornflake': 'Mornflake',
 'hengstenberg': 'Hengstenberg',
 'naked noodle': 'Naked Noodle',
 'mellow birds': "Mellow Bird's",
 'aunt bessies': "Aunt Bessie's",
 'lu': 'LU',
 'frenchs': "French's",
 'edlers': 'Edlers',
 'nielsen massey': 'Nielsen-Massey',
 'encona': 'Encona',
 'total sweet': 'Total Sweet',
 'whitby': 'Whitby',
 'kirstys': "Kirsty's",
 'newmans own': "Newman's Own",
 'taste the difference': 'Taste the Difference',
 'xxx': 'XXX',
 'ricola': 'Ricola',
 'big hoops': 'Big Hoops',
 'olivio': 'Olivio',
 'good4u': 'GOOD4U',
 'vivera': 'Vivera',
 'manomasa': 'Manomasa',
 'illy': 'illy',
 'hunger breaks': 'Hunger Breaks',
 'wasabi': 'Wasabi',
 'duerrs': "Duerr's",
 'sunbites': 'Sunbites',
 'cholula': 'Cholula',
 'pek': 'Pek',
 'lift': 'Lift',
 'franks': 'Franks',
 'nuii': 'Nuii',
 'tea india': 'Tea India',
 'alara': 'Alara',
 'carte noire': 'Carte Noire',
 'food thoughts': 'Food Thoughts',
 'rubicon': 'Rubicon',
 'specialite locale': 'Specialite Locale',
 'hermesetas': 'Hermesetas',
 'trophy': 'Trophy',
 'airwaves': 'Airwaves',
 'up go': 'Up & Go',
 'ting': 'Ting',
 'bfree': 'BFree',
 'grace green': 'Grace Green',
 'too good to be gluten free': 'Too Good To Be Gluten Free',
 'nomo': 'NOMO',
 'vifon': 'Vifon',
 'mr freeze': 'Mr. Freeze',
 'bio me': 'Bio & Me',
 'capsicana': 'Capsicana',
 'promise': 'Promise',
 'jack links': "Jack Link's",
 'flying goose': 'Flying Goose',
 'thorntons': 'Thorntons',
 'jif lemon': 'Jif Lemon',
 'leon': 'LEON',
 'barilla': 'Barilla',
 'tropical sun': 'Tropical Sun',
 'bute island foods ltd': 'Bute Island Foods Ltd',
 'azeem': 'Azeem',
 'montezumas': 'Montezuma’s',
 'cardinis': "Cardini's",
 'farringtons': "Farrington's",
 'jimjams': 'JimJams',
 'pieminister': 'Pieminister',
 'drink me': 'Drink Me',
 'whole creations': 'Whole Creations',
 'love corn': 'LOVE CORN',
 'coffee mate': 'Coffee Mate',
 'pure via': 'Pure Via',
 'piatnica': 'Piatnica',
 'sweet freedom': 'Sweet Freedom',
 'lazy day foods': 'Lazy Day Foods',
 'mlekovita': 'Mlekovita',
 'naked rice': 'Naked Rice',
 'peroni': 'Peroni',
 'almondy': 'Almondy',
 'grace': 'Grace',
 'monin': 'Monin',
 'extra ice': 'Extra Ice',
 'huel': 'Huel',
 'sun hee': 'Sun Hee',
 'krasnystaw': 'Krasnystaw',
 'hillfarm': 'Hillfarm',
 'dairylea': 'Dairylea',
 'mary berrys': "Mary Berry's",
 'hilltop honey': 'Hilltop Honey',
 'stoats': 'Stoats',
 'nongshim': 'Nongshim',
 'sch r': 'Schär',
 'ferrero': 'Ferrero',
 'wonderful': 'Wonderful',
 'reeses': "Reese's",
 'laila': 'Laila',
 'kinnerton': 'Kinnerton',
 'vita': 'Vita',
 'najma': 'Najma',
 'forest feast': 'Forest Feast',
 'cerebos': 'Cerebos',
 'jubbly': 'Jubbly',
 'tracker': 'Tracker',
 'shredded wheat': 'Shredded Wheat',
 'red bull': 'Red Bull',
 'jutrzenka': 'Jutrzenka',
 'bulls eye': "Bull's-Eye",
 'natures store': "Nature's Store",
 'sweet baby rays': "Sweet Baby Ray's",
 'mighty': 'Mighty',
 'halo top': 'Halo Top',
 'crazy jack': 'Crazy Jack',
 'malay taste': 'Malay Taste',
 'tassimo kenco': 'Tassimo Kenco',
 'tic tac': 'Tic Tac',
 'judes': 'Judes',
 'mlekpol': 'Mlekpol',
 'caf direct': 'Cafédirect',
 'discos': 'Discos',
 'pride': 'Pride',
 'natco': 'Natco',
 'gourmet burger kitchen': 'Gourmet Burger Kitchen',
 'naked': 'Naked',
 'cheetos': 'Cheetos',
 'galbani': 'Galbani',
 'kabuto': 'Kabuto',
 'weetos': 'Weetos',
 'tariq': 'Tariq',
 'shana': 'Shana',
 'nurishment': 'Nurishment',
 'mrs balls': 'Mrs Balls',
 'daura damm': 'Daura Damm',
 'quaker oat': 'Quaker Oat',
 'hendersons': "Henderson's",
 'white rabbit': 'White Rabbit',
 'riesen': 'Riesen',
 'yum yay': 'Yum & Yay',
 'osem': 'Osem',
 'costa': 'Costa',
 'la chinata': 'La Chinata',
 'stokes': 'Stokes',
 'salaam': 'Salaam',
 'stute': 'Stute',
 'laciate': 'Laciate',
 'gran luchito': 'Gran Luchito',
 'tulip': 'Tulip',
 'choccie dodgers': 'Choccie Dodgers',
 'lucy bee': 'Lucy Bee',
 'elizabeth shaw': 'Elizabeth Shaw',
 'la monegasque': 'La Monegasque',
 'mentos': 'Mentos',
 'nutri brex': 'Nutri-Brex',
 'the paleo foods co': 'The Paleo Foods Co.',
 'manilife': 'ManiLife',
 'winiary': 'Winiary',
 'dairy box': 'Dairy Box',
 'the natural confectionery company': 'The Natural Confectionery Company',
 'popworks': 'Popworks',
 'naturya': 'Naturya',
 'tiger': 'Tiger',
 'jelly belly': 'Jelly Belly',
 'milo': 'Milo',
 'bosh nooch': 'Bosh! Nooch!',
 'union': 'Union',
 'prymat': 'Prymat',
 'linghams': "Lingham's",
 'teapigs': 'Teapigs',
 'mr crumb': 'Mr. Crumb',
 'piriteze': 'Piriteze',
 'miso tasty': 'Miso Tasty',
 'cadburys': 'Cadburys',
 'morliny': 'Morliny',
 'mister freed': "Mister Free'd",
 'rhythm 108': 'Rhythm 108',
 'milka': 'Milka',
 'kedem': 'Kedem',
 'inferno': 'Inferno',
 'sokolow': 'Sokolow',
 'extra cool breeze': 'Extra Cool Breeze',
 'lily obriens': "Lily O'Brien's",
 'bunlimited': 'Bunlimited',
 'simplee aloe': 'Simplee Aloe',
 'littles': "Little's",
 'mallow marsh': 'Mallow & Marsh',
 'maryland cookies': 'Maryland Cookies',
 'greens': "Green's",
 'kubus mus': 'Kubus Mus',
 'alfez': "Al'Fez",
 'tarczynski': 'Tarczynski',
 'virtu': 'Virtu',
 'tariq halal': 'Tariq Halal',
 'difatti': 'Difatti',
 'beanies': 'Beanies',
 'monster munch': 'Monster Munch',
 'reds': "Red's",
 'lazyday': 'Lazyday',
 'pink panther': 'Pink Panther',
 'la espanola': 'La Espanola',
 'brunswick': 'Brunswick',
 'bacofoil': 'Bacofoil',
 'supermalt': 'Supermalt',
 'lowicz': 'Lowicz',
 'squid brand': 'Squid Brand',
 'grzeski': 'Grzeski',
 'taste inc': 'Taste Inc.',
 'walkers nonsuch': "Walker's Nonsuch",
 'violife': 'Violife',
 'tiger zero': 'Tiger Zero',
 'sauce shop': 'Sauce Shop',
 'profi': 'Profi',
 'celebrations': 'Celebrations',
 'fulfil': 'FULFIL',
 'bangthai': 'Bangthai',
 'yayu forest': 'Yayu Forest',
 'ka': 'KA',
 'ginsters': 'Ginsters',
 'muszynianka': 'Muszynianka',
 'buttermilk': 'Buttermilk',
 'skittles': 'Skittles',
 'plant pioneers': 'Plant Pioneers',
 'wedel': 'Wedel',
 'raw bean': 'Raw Bean',
 'potts': "Potts'",
 'risana': 'Risana',
 'squeaky bean': 'Squeaky Bean',
 'tymbark': 'Tymbark',
 'marshmallow fluff': 'Marshmallow Fluff',
 'jfc': 'JFC',
 'good earth': 'Good Earth',
 'santa maria': 'Santa Maria',
 'cake angels': 'Cake Angels',
 'sun pat': 'Sun-Pat',
 'howdah': 'Howdah',
 'raffaello': 'Raffaello',
 'mieszko': 'Mieszko',
 'hilltop': 'Hilltop',
 'paw patrol': 'Paw Patrol',
 'monty bojangles': 'Monty Bojangles',
 'bakery delights': 'Bakery Delights',
 'the chia co': 'The Chia Co',
 'kucharek': 'Kucharek',
 'henna': 'Henna',
 'dr kargs': "Dr. Karg's",
 'fruittella': 'Fruittella',
 'wilkin sons ltd tiptree': 'Wilkin & Sons Ltd Tiptree',
 'fanta': 'Fanta',
 'honey monster': 'Honey Monster',
 'ortiz el velero': 'Ortiz El Velero',
 'walkers shortbread': "Walker's Shortbread",
 'allinsons': "Allinson's",
 'loasis de djerba': "L'Oasis de Djerba",
 'oshee': 'Oshee',
 'go free': 'Go Free',
 'bart': 'Bart',
 'aleyna': 'Aleyna',
 'yo': 'YO!',
 'kohinoor': 'Kohinoor',
 'harleys': "Harley's",
 'rhythm108': 'Rhythm108',
 'certo': 'Certo',
 'vitasoy': 'Vitasoy',
 'marigold health foods': 'Marigold Health Foods',
 'grants': "Grant's",
 'creative nature': 'Creative Nature',
 'bold bean co': 'Bold Bean Co',
 'chupa chups': 'Chupa Chups',
 'wholecreations': 'Wholecreations',
 'union hand roasted': 'Union Hand-Roasted',
 'ribena': 'Ribena',
 'littleover apiaries': 'Littleover Apiaries',
 'pukka organic': 'Pukka Organic',
 'kubus': 'Kubus',
 'patum peperium': 'Patum Peperium',
 'daim': 'Daim',
 'fentimans': 'Fentimans',
 'dinos': "Dino's",
 'magija': 'Magija',
 'regal': 'Regal',
 'house of cake': 'House of Cake',
 'cafedirect': 'Cafedirect',
 'good guys bakehouse': 'Good Guys Bakehouse',
 'east end': 'East End',
 'taijade': 'Taijade',
 'union gajah': 'Union Gajah',
 'pakeeza': 'Pakeeza',
 'g': 'Gü',
 'jezyki': 'Jezyki',
 'lungkow': 'Lungkow',
 'krakus': 'Krakus',
 'tassimo lor': "Tassimo L'OR",
 'island sun': 'Island Sun',
 'rymut': 'Rymut',
 'malt o meal': 'Malt O Meal',
 'akash gold': 'Akash Gold',
 'graal': 'Graal',
 'thai dragon': 'Thai Dragon',
 'wagamama': 'Wagamama',
 'kettle': 'Kettle',
 'barebells': 'Barebells',
 'candy kittens': 'Candy Kittens',
 'gefen': 'Gefen',
 'space raiders': 'Space Raiders',
 'loasis': "L'oasis",
 'old speckled hen': 'Old Speckled Hen',
 'wilkin sons ltd': 'Wilkin & Sons Ltd',
 'taj': 'Taj',
 'good hemp': 'Good Hemp',
 'pyrex': 'Pyrex',
 'familijne': 'Familijne',
 'pots co': 'Pots & Co',
 'kimura': 'Kimura',
 'regal bakery': 'Regal Bakery',
 'hip pop': 'Hip Pop',
 'prince polo': 'Prince Polo',
 'taylor colledge': 'Taylor & Colledge',
 'kotlin': 'Kotlin',
 'cake decor': 'Cake Decor',
 'charlie bighams': "Charlie Bigham's",
 'goldfish brand': 'Goldfish Brand',
 'starburst': 'Starburst',
 'ueshima coffee company': 'Ueshima Coffee Company',
 'oddpods': 'Oddpods',
 'flying goose brand': 'Flying Goose Brand',
 'willys organic': "Willy's Organic",
 'lazy day': 'Lazy Day',
 'no 1': 'No.1',
 'baldwins': 'Baldwins',
 'good boy': 'Good Boy',
 'felix': 'Felix',
 'lorenz': 'Lorenz',
 'brooklyn dinos': "Brooklyn Dino's",
 'mighty fine': 'Mighty Fine',
 'the curators': 'The Curators',
 'jammie dodgers': 'Jammie Dodgers',
 'przysnacki': 'Przysnacki',
 'dega': 'Dega',
 'lubella': 'Lubella',
 'oggs': 'OGGS',
 'natural gold': 'Natural Gold',
 'bens': "Ben's",
 'blue riband': 'Blue Riband',
 'doisy dam': 'Doisy & Dam',
 'kubus water': 'Kubus Water',
 'achva': 'Achva',
 'e wedel': 'E. Wedel',
 'proper': 'Proper',
 'proper chips': 'Proper Chips',
 'manischewitz': 'Manischewitz',
 'frugo': 'Frugo',
 'renshaw': 'Renshaw',
 'muttil': 'Muttil',
 'excelsior': 'Excelsior',
 'richmond': 'Richmond',
 'tracklements': 'Tracklements',

In [32]:
brand_df.head(4)

                                             product                brand
0           Maryland Cookies Chocolate Chip Minis x6             Maryland
1                                Weetabix Cereal x24             Weetabix
2               Walker's Shortbread Fingers x10 160g             Walker's
3  Stamford Street Co. Chopped Tomatoes in Tomato...  Stamford Street Co.

In [33]:
def map_brands_normalized(df, brand_map, text_col="names"):
    import re
    
    df = df.copy()
    
    # normalize product names
    names = df[text_col].fillna("").str.lower()
    names = names.str.replace(r"[’']", "", regex=True)
    names = names.str.replace(r"[^a-z0-9\s]", " ", regex=True)
    names = names.str.replace(r"\s+", " ", regex=True).str.strip()
    
    # sort normalized brands
    brands = sorted(brand_map.keys(), key=len, reverse=True)
    
    pattern = r'\b(' + '|'.join(map(re.escape, brands)) + r')\b'
    
    # extract normalized match
    df["Brand_norm"] = names.str.extract(pattern, expand=False)
    
    # map back to original brand
    df["Brand"] = df["Brand_norm"].map(brand_map)
    
    # fallback
    df["Brand"] = df["Brand"].fillna("Unknown")
    
    return df.drop(columns=["Brand_norm"])

In [34]:
mapped_brand_list = map_brands_normalized(third_party_brands, brand_map, text_col="names")

In [40]:
mapped_brand_list['Brand'].value_counts()

Brand
Unknown                1164460
L'Oreal Paris            26323
Cadbury                  16817
Extra                    16670
Stamford Street Co.      15939
                        ...
Special K                   19
Koikeya                     18
Chef                        16
J-Basket                    10
Baking Buddy                 8
Name: count, Length: 985, dtype: int64

##### Brand List

In [67]:
brand_df['brand'].value_counts()

brand
Cadbury          232
Heinz            144
Walkers           88
Kellogg's         88
Twinings          81
                ...
Kitkat             1
Oggs               1
Ben & Jerry's      1
Pulsin             1
J-Basket           1
Name: count, Length: 1046, dtype: int64